Fix test_clifford.TestClifford.test_normalInv
Under Windows with numba<0.60 the test fails in JIT-ted hitzer_inverse
function with:
> numba.core.errors.TypingError: Failed in nopython mode pipeline...
Actual cause is unclean, must be some Windows specific JIT compilation
issue in earlier numba versions.

This fix reverts the changes in _layout.Layout._hitzer_inverse made by
commit 61e373ea0ec7b0a9e1edbd47cd730346bd8283e3.